#include "content.h"
#include <stddef.h>

/* Problem indices, in the order of PROBS below */
enum { PR_SKIP, PR_SLOWUP, PR_SLOWDOWN, PR_SPOKES, PR_DROPOUT, PR_HANGER, PR_FDRUB, PR_DROP, PR_NOISY,
       PR_LEVERBAR, PR_SPONGY, PR_WEAK, PR_RUB, PR_FLAT, PR_WOBBLE, PR_FREEHUB, PR_HEADSET, PR_NOTCHY,
       PR_CREAK, PR_SADDLE, PR_SHIFTER };

const char *GROUP_NAMES[G_COUNT] = { "Frame & fork", "Drivetrain", "Brakes & controls", "Wheels & tyres", "Contact points" };
const char *SYS_NAMES[SYS_N] = { "Shifting", "Drivetrain", "Brakes", "Wheels", "Steering & frame", "Noises" };

#define END -1
const PartInfo PARTS[P_COUNT] = {
 { "Frame", G_FRAME,
   "The aluminium structure everything bolts to. Its tube angles set how the bike steers and fits; its stiffness decides how much pedalling force reaches the back wheel instead of flexing the frame.",
   "E5 Premium aluminium, hydroformed tubes, internal cable routing, threaded bottom bracket, flat-mount disc mounts, 12×142 mm rear thru-axle. Clearance for roughly 47 mm tyres.",
   "Look for cracks near welds (head tube, bottom bracket, dropouts) after any crash. Paint cracking in a ring around a tube is a warning sign.",
   { P_FORK, P_BB, P_HEADSET, P_SEATPOST, P_HANGER, P_THRUAXLE, END }, { PR_CREAK, END }, -1,
   {631, 517, 0}, 2600, 20, 12 },
 { "Fork", G_FRAME,
   "Holds the front wheel and turns with the handlebar. Its forward bend (offset) and the head angle together create trail, which is what makes the bike want to go straight.",
   "Carbon blades, 12×100 mm thru-axle, flat-mount brake. Some Diverge models use Future Shock suspension in the head tube; the E5 base is rigid.",
   "Hold the front brake and rock the bike. A knock here is usually the headset, not the fork.",
   { P_HEADSET, P_THRUAXLE, P_CALIPERS, P_COCKPIT, END }, { PR_HEADSET, PR_RUB, END }, B_STEER,
   {940, 560, 0}, 1400, 35, 8 },
 { "Headset", G_FRAME,
   "Two cartridge bearings in the head tube let the fork steer smoothly. The top cap bolt sets preload, squeezing the bearings just enough to remove play; the stem bolts then lock that setting in.",
   "Tapered steerer: 1 1/8 in top bearing, 1 1/2 in bottom bearing, sealed cartridges.",
   "Front brake on, rock the bike back and forth with a hand around the top bearing. Feel for a clunk.",
   { P_FORK, P_COCKPIT, P_FRAME, END }, { PR_HEADSET, PR_NOTCHY, END }, B_STEER,
   {828, 800, 0}, 650, 35, 10 },
 { "Stem & handlebar", G_CONTACT,
   "The stem clamps the steerer and the bar; the bar holds the levers. A flared gravel drop bar gives more control in the drops.",
   "Alloy stem (length scales with frame size), flared alloy drop bar.",
   "Stand over the front wheel, grip it between your knees and twist the bar. It must not move.",
   { P_HEADSET, P_LEVERS, P_FORK, END }, { PR_HEADSET, END }, B_STEER,
   {900, 880, 0}, 1000, 40, 18 },
 { "Shift/brake levers", G_BRAKE,
   "Each lever does two jobs. Pull the blade back to brake. Swing it sideways to shift: the right lever moves the rear derailleur, the left moves the front.",
   "Base: Claris mechanical levers pulling brake and gear cables. Elite-type: GRX levers with a hydraulic master cylinder for the brakes.",
   "Each shift click should feel crisp. A lever that moves with no resistance usually means a snapped cable inside.",
   { P_CABLES, P_RD, P_FD, P_CALIPERS, END }, { PR_SHIFTER, PR_LEVERBAR, PR_SPONGY, END }, B_BRAKES,
   {965, 875, 210}, 600, 55, 12 },
 { "Cables, housing & hoses", G_BRAKE,
   "Steel inner cables slide inside housing to carry lever pull to the derailleurs and, on mechanical brakes, the calipers. Hydraulic builds use sealed hoses filled with mineral oil instead.",
   "Routed inside the frame. Shift housing is compressionless; brake housing is spiral-wound.",
   "Frayed ends, kinks, rust and gritty movement all cause sluggish shifting. New cables stretch slightly in the first few rides.",
   { P_LEVERS, P_RD, P_FD, P_CALIPERS, END }, { PR_SLOWUP, PR_SLOWDOWN, PR_LEVERBAR, PR_SHIFTER, END }, B_RD,
   {860, 790, 0}, 1100, 30, 10 },
 { "Seatpost & clamp", G_CONTACT,
   "Sets saddle height. The clamp squeezes the top of the seat tube around the post.",
   "27.2 mm alloy post. A longer exposed post flexes more, which adds comfort.",
   "Mark the post at the clamp with tape. If the mark moves, see \"Seatpost slips\".",
   { P_SADDLE, P_FRAME, END }, { PR_SADDLE, PR_CREAK, END }, -1,
   {245, 880, 0}, 800, 25, 10 },
 { "Saddle", G_CONTACT,
   "Carries most of your weight. Rails let you slide it forward and back and tilt it.",
   "Specialized Bridge-type saddle on most E5 builds.",
   "Saddle-rail clamp bolts loosen over time and are a common creak source.",
   { P_SEATPOST, END }, { PR_SADDLE, PR_CREAK, END }, -1,
   {215, 1025, 0}, 800, 25, 20 },
 { "Bottom bracket", G_DRIVE,
   "Bearings in the frame's bottom bracket shell that the crank axle spins in. Everything you put into the pedals passes through here.",
   "Threaded BSA, 68 mm shell, external cups. Threaded is the easy kind: remove, clean, grease, refit.",
   "Remove the chain and spin the cranks: they should turn smoothly with no grinding. Rock a crank sideways to check for play.",
   { P_CRANKSET, P_FRAME, END }, { PR_CREAK, END }, B_STEER,
   {419, 279, 0}, 650, 30, 5 },
 { "Crankset & chainrings", G_DRIVE,
   "The crank arms turn your leg force into torque; the chainrings turn that torque into chain tension. Two rings give a high and a low range.",
   "Two chainrings, 170–172.5 mm arms depending on frame size.",
   "Look for bent or shark-fin-shaped teeth. Check the chainring bolts and crank pinch bolts are tight.",
   { P_BB, P_CHAIN, P_PEDALS, P_FD, END }, { PR_DROP, PR_CREAK, PR_NOISY, END }, B_GEARING,
   {419, 279, 50}, 900, 15, 5 },
 { "Pedals", G_CONTACT,
   "Your contact with the drivetrain. Threaded into the cranks: the left pedal has a reverse thread, so pedalling tightens both.",
   "Flat pedals on most E5s. 9/16 in thread.",
   "A click once per pedal stroke is often a dry pedal thread. Remove, grease, refit.",
   { P_CRANKSET, END }, { PR_CREAK, END }, -1,
   {419, 279, 120}, 1000, 25, 10 },
 { "Chain", G_DRIVE,
   "Carries tension from the chainring to the cassette along its top run. The bottom run carries no load; the rear derailleur keeps it taut. It is narrow enough to slip between cogs when pushed sideways, which is how shifting works.",
   "Base: 8-speed chain. Elite-type: 10-speed chain. Do not mix speeds.",
   "Use a chain checker. Replace at 0.75% elongation on 8/10-speed (0.5% on 11/12-speed). A new chain costs far less than the cassette and rings an old one wears out.",
   { P_CRANKSET, P_CASSETTE, P_RD, P_FD, END }, { PR_SKIP, PR_NOISY, END }, B_GEARING,
   {210, 315, 45}, 1100, 15, 8 },
 { "Front derailleur", G_DRIVE,
   "A cage around the chain just above the chainrings. Pull the cable and it pushes the chain outward onto the big ring; release it and a spring pulls it back to the small ring.",
   "Braze-on mount, cable pull from below. Two limit screws (H and L) and a trim position on the big ring.",
   "The outer cage plate should sit 1–3 mm above the big ring's teeth and parallel to the ring.",
   { P_CHAIN, P_CRANKSET, P_CABLES, P_LEVERS, END }, { PR_FDRUB, PR_DROP, END }, B_FD,
   {372, 360, 48}, 550, 20, 15 },
 { "Rear derailleur", G_DRIVE,
   "A spring-loaded parallelogram that moves the chain across the cassette. Cable pull moves it toward bigger cogs; its spring returns it to smaller cogs. Its cage also takes up chain slack.",
   "Base: Claris 8-speed. Elite-type: GRX 10-speed. Barrel adjuster at the cable entry, H and L limit screws, B-tension screw.",
   "Look from behind: the two jockey wheels should line up vertically under the cog they're on.",
   { P_HANGER, P_CASSETTE, P_CHAIN, P_CABLES, P_LEVERS, END }, { PR_SKIP, PR_SLOWUP, PR_SLOWDOWN, PR_SPOKES, PR_DROPOUT, PR_HANGER, END }, B_RD,
   {5, 285, 60}, 600, 25, 8 },
 { "Derailleur hanger", G_DRIVE,
   "A small, deliberately soft aluminium plate between frame and derailleur. In a crash it bends or snaps so the frame doesn't. A slightly bent hanger is the hidden cause of a lot of bad shifting.",
   "Replaceable and specific to this frame. Keep a spare; they're cheap.",
   "Look from behind: the derailleur should hang straight down in line with the cassette.",
   { P_RD, P_FRAME, P_THRUAXLE, END }, { PR_HANGER, PR_SKIP, END }, B_RD,
   {8, 330, 72}, 420, -40, 10 },
 { "Cassette", G_DRIVE,
   "The stack of rear cogs. Small cogs are hard gears; big cogs are easy gears. Ramps and pins on each cog help the chain climb between them.",
   "Base: 8-speed. Elite-type: 10-speed. Slides onto the freehub splines and is held by a lockring.",
   "If a new chain skips on the cogs you use most, the cassette is worn too.",
   { P_CHAIN, P_RD, P_HUBS, END }, { PR_SKIP, PR_NOISY, END }, B_GEARING,
   {0, 349, 44}, 600, 25, 8 },
 { "Hubs & freehub", G_WHEEL,
   "Bearings let the wheels spin on their axles. The rear hub has a freehub: spring-loaded pawls grip a toothed ring when you pedal and click past it when you coast.",
   "Sealed-bearing hubs, 12 mm thru-axles front and rear.",
   "With the wheel in the bike, try to wiggle the rim sideways. Play there means hub bearings.",
   { P_CASSETTE, P_WHEELS, P_ROTORS, P_THRUAXLE, END }, { PR_FREEHUB, PR_WOBBLE, END }, B_WHEELS,
   {0, 349, 0}, 700, 30, 5 },
 { "Rims & spokes", G_WHEEL,
   "Spokes hang the hub from the rim under tension. Torque from the hub (pedalling at the back, braking at both ends) travels through the spokes to the rim.",
   "Alloy rims, 700c, 24–28 spokes. Tubeless-ready on many E5 wheelsets.",
   "Spin each wheel and watch the gap at the frame or fork. A wobble you can see needs truing.",
   { P_TIRES, P_HUBS, P_ROTORS, END }, { PR_WOBBLE, PR_FLAT, END }, B_WHEELS,
   {1248, 561, 0}, 1700, 20, 5 },
 { "Tyres", G_WHEEL,
   "Your suspension and your grip. Pressure decides how big the contact patch is, how much the tyre absorbs bumps, and how likely a pinch flat is.",
   "700×38 mm gravel tyres on most E5s.",
   "Check pressure before every ride. Gravel tyres lose air faster than you expect.",
   { P_WHEELS, END }, { PR_FLAT, END }, B_WHEELS,
   {-233, 116, 0}, 1700, 20, 5 },
 { "Thru-axles", G_FRAME,
   "A 12 mm bolt-through axle passes through the dropouts and hub and threads into the far side. It locates the wheel exactly, so the disc rotor lands in the same place every time.",
   "12×100 mm front, 12×142 mm rear.",
   "Tighten by hand to the torque printed on the axle. A loose axle causes creaks, brake rub and vague shifting.",
   { P_HUBS, P_FORK, P_FRAME, P_HANGER, END }, { PR_RUB, PR_CREAK, PR_WOBBLE, END }, B_WHEELS,
   {1036, 349, -60}, 650, 160, 10 },
 { "Disc rotors", G_BRAKE,
   "Steel discs bolted to the hubs, on the left side of the bike. The pads squeeze them to turn speed into heat.",
   "160 mm front and rear on most sizes.",
   "Spin the wheel and look through the caliper slot. A rotor that wavers will tick against the pads once per turn.",
   { P_CALIPERS, P_HUBS, END }, { PR_RUB, PR_WEAK, END }, B_BRAKES,
   {0, 349, -58}, 750, 155, 10 },
 { "Brake calipers", G_BRAKE,
   "Hold the pads either side of the rotor. Mechanical calipers push one pad with a cam and flex the rotor onto the fixed pad. Hydraulic calipers push both pads with oil pressure.",
   "Base: cable-actuated mechanical discs. Elite-type: Shimano hydraulic. Flat mount front and rear.",
   "Look in from above with a torch: pads should have at least 0.5 mm of material left on the backing plate.",
   { P_ROTORS, P_CABLES, P_LEVERS, P_FORK, P_FRAME, END }, { PR_LEVERBAR, PR_SPONGY, PR_WEAK, PR_RUB, END }, B_BRAKES,
   {78, 366, -58}, 520, 160, 25 },
};

const Problem PROBS[] = {
 { "Chain skips or jumps under load", "Pedals slip for a moment when you push hard, or it changes gear by itself.",
   SYS_SHIFT | SYS_DRIVE | SYS_NOISE, 2, "10–30 min", "Easy",
   { "Cable tension slightly off: the guide pulley sits between two cogs.", "Worn chain and cassette: an elongated chain rides up the cog teeth.",
     "Bent derailleur hanger, usually after the bike fell on its right side.", "Stiff chain link: the derailleur cage jumps once per chain revolution.", NULL },
   "Pedal on a stand in each gear. Skipping in one gear points to tension. Skipping in your most-used gears points to wear: measure the chain.",
   { "Shift to the big ring and second-smallest cog. Turn the cranks forward.",
     "If the chain rattles toward the next bigger cog, turn the barrel adjuster a quarter turn clockwise (less tension). If it hesitates or rattles toward the smaller cog, turn it a quarter turn anticlockwise (more tension).",
     "Shift through every cog; repeat quarter-turn tweaks until each change is one crisp click.",
     "Measure the chain. At 0.75% or more, replace it. If the new chain skips on your favourite cogs, replace the cassette too.",
     "If shifting is good in the middle but poor at the ends, check the hanger.", NULL },
   "Hands for the barrel adjuster; chain checker; chain tool or quick-link pliers.", "the hanger looks bent and you don't have a hanger alignment gauge.",
   { P_CHAIN, P_CASSETTE, P_RD, P_HANGER, P_CABLES, END }, B_RD },
 { "Won't climb to bigger cogs", "You click the lever and it takes a second click, or a pedal stroke, to move to an easier gear.",
   SYS_SHIFT, 1, "5 min", "Easy",
   { "Cable too slack: new cables stretch and housing ends settle in the first rides.", "L limit screw too tight, if only the biggest cog won't go.", "Sticky cable: dirt or corrosion inside the housing.", NULL },
   "Look from behind in a middle gear: the guide pulley sits slightly outboard of the cog it's on.",
   { "Shift to a middle cog.", "Turn the barrel adjuster anticlockwise (seen from the cable side) half a turn to add tension.",
     "Test shifts up and down; add or take back quarter turns until each click moves one cog.",
     "If the adjuster runs out of thread, screw it back in, shift to the smallest cog, loosen the cable clamp bolt, pull the cable snug by hand and retighten.", NULL },
   "Hands; 5 mm hex if re-clamping the cable.", "the cable feels gritty and the lever action is heavy. Re-routing housing through an internally routed frame is fiddly.",
   { P_CABLES, P_RD, P_LEVERS, END }, B_RD },
 { "Slow to drop to smaller cogs", "The release lever clicks but the chain lingers, then drops late.",
   SYS_SHIFT, 1, "5–40 min", "Easy",
   { "Cable too tight: the pulley sits inboard of the cog.", "Friction in the housing: the derailleur spring can't pull a dirty cable back.", "Dry derailleur pivots.", NULL },
   "Shift to the smallest cog, then pull the bare cable away from the frame by hand and let go. It should snap back.",
   { "Turn the barrel adjuster a quarter turn clockwise and re-test.", "If tension is right but it's still slow, put a drop of light oil on the derailleur pivots.",
     "If still slow, the housing is dirty or kinked: replace the inner cable and housing.", NULL },
   "Hands; light oil; cable cutters for housing.", "you need to re-route housing through the frame and have no internal-routing guide.",
   { P_CABLES, P_RD, END }, B_RD },
 { "Chain goes past the biggest cog into the spokes", "Overshift on the easiest gear. Stop riding: this can wreck the wheel and derailleur.",
   SYS_SHIFT, 3, "5 min", "Easy",
   { "L limit screw too loose.", "Bent hanger pushing the derailleur inward.", NULL },
   "Shift to the biggest cog and push the derailleur body inward with your thumb while slowly turning the cranks. The chain must not climb past the cog.",
   { "Shift to the largest cog.", "Turn the L screw clockwise in quarter turns until the guide pulley sits exactly under the largest cog and pushing the derailleur inward can't move it further.",
     "Shift up and down to confirm it still reaches the largest cog easily.", "Check the hanger and spokes for damage.", NULL },
   "Small Phillips screwdriver or 2 mm hex.", "spokes are bent or the derailleur cage is twisted.",
   { P_RD, P_WHEELS, END }, B_RD },
 { "Chain drops off the smallest cog", "The chain jams between the smallest cog and the frame.",
   SYS_SHIFT, 3, "5 min", "Easy",
   { "H limit screw too loose.", NULL },
   "In the smallest cog, look from behind. The guide pulley should sit directly under the smallest cog, not outside it.",
   { "Shift to the smallest cog and let the cable go fully slack.", "Turn the H screw clockwise until the guide pulley lines up with the outer edge of the smallest cog.",
     "Shift up one cog and back to confirm it still drops crisply.", NULL },
   "Small Phillips screwdriver or 2 mm hex.", "the frame near the dropout is deeply gouged.",
   { P_RD, P_FRAME, END }, B_RD },
 { "Good in the middle, bad at the ends", "Shifting went vague after the bike fell over or travelled in a car.",
   SYS_SHIFT, 2, "10–20 min", "Medium",
   { "Bent derailleur hanger. The error grows the further the pulley hangs below the hanger, so big cogs suffer most.", NULL },
   "Stand behind the bike and line your eye up with the cassette. The derailleur cage should be parallel to the cogs. If it toes in at the bottom, the hanger is bent.",
   { "Remove the rear wheel; keep the derailleur attached.", "Thread a hanger alignment gauge into the derailleur bolt hole (or take it to a shop).",
     "Bend gently back in small steps, checking at four points around the rim.", "Or replace the hanger: one bolt, one derailleur bolt. Fit it, then re-index the gears.", NULL },
   "Hanger alignment gauge, or a replacement hanger and 4/5 mm hex.", "you don't own an alignment gauge. Never bend a hanger by pulling on the derailleur body.",
   { P_HANGER, P_RD, END }, B_RD },
 { "Chain rubs the front derailleur", "A scraping noise in some gears, often on the extreme cogs.",
   SYS_SHIFT | SYS_NOISE, 1, "5–15 min", "Easy",
   { "Cross-chaining: big ring with the largest cogs, or small ring with the smallest cogs.", "Not using trim: Claris and GRX levers have a half-click on the big ring that nudges the cage inward.", "Front cable slack, or limit screws off.", NULL },
   "Note which ring and cog rub. Rub only at the extremes is normal; rub across the middle cogs needs adjusting.",
   { "Try the trim click first: on the big ring, a small push on the left shift lever moves the cage slightly inward.", "Avoid big-big and small-small; the other ring has a similar gear with a straighter chain.",
     "If it still rubs in the middle cogs, adjust cable tension at the inline barrel adjuster in quarter turns.", "Set the limit screws only if the extremes can't be cleared.", NULL },
   "Hands; small screwdriver for limit screws.", "the derailleur cage is bent or the mount has slipped.",
   { P_FD, P_CHAIN, P_CABLES, END }, B_FD },
 { "Chain falls off the chainrings", "The chain drops inside onto the frame on a downshift, or flies off outside on an upshift.",
   SYS_SHIFT | SYS_DRIVE, 2, "10 min", "Easy",
   { "L limit too loose: the cage swings too far inward and throws the chain off the small ring.", "H limit too loose: the cage throws the chain over the big ring.", "Bumpy terrain with a slack chain, common on gravel.", NULL },
   "Shift the front slowly while turning the cranks on a stand. Watch where the chain leaves the rings.",
   { "Inside drop: small ring and largest cog. Turn the L screw clockwise until the inner cage plate is 0.5–1 mm from the chain.",
     "Outside drop: big ring and smallest cog. Turn the H screw clockwise until the outer plate is 0.5–1 mm from the chain.",
     "Test every front shift with the chain on each extreme rear cog.", "On rough gravel, shift the front before a climb, not during it.", NULL },
   "Small screwdriver.", "the cage height or angle needs resetting, or the clamp has slipped.",
   { P_FD, P_CRANKSET, P_CHAIN, END }, B_FD },
 { "Squeaky, grinding or noisy drivetrain", "A squeal, crunch or general roughness that follows the pedals.",
   SYS_DRIVE | SYS_NOISE, 1, "15–40 min", "Easy",
   { "Dry chain: squeaks, worse after rain.", "Gritty chain: crunching after gravel or mud.", "Worn chain: a rough, vague feel.", "Dry jockey wheels in the rear derailleur.", NULL },
   "Run a fingertip along the chain. Black grit means clean before you lube.",
   { "Wipe the chain with a rag while back-pedalling. For heavy grit, use degreaser and a brush, then rinse and dry.", "Put one drop of lube on each roller, on the inside of the chain.",
     "Back-pedal for 30 seconds, then wipe off the excess. Lube on the outside only collects dirt.", "Measure wear with a chain checker.", NULL },
   "Rags, degreaser, chain lube, chain checker.", "grinding persists with a clean chain: likely jockey wheel or bottom bracket bearings.",
   { P_CHAIN, P_CASSETTE, P_CRANKSET, P_RD, END }, B_GEARING },
 { "Brake lever pulls almost to the bar", "Mechanical discs: the lever travels a long way before the brake bites.",
   SYS_BRAKE, 3, "10 min", "Easy",
   { "Pad wear: mechanical calipers don't self-adjust, so every 0.5 mm of wear adds lever travel.", "Cable stretch: new cables lengthen in the first weeks.", NULL },
   "Look into the caliper from above. Pads under 0.5 mm need replacing, not adjusting.",
   { "Turn the inner-pad adjuster on the caliper (where fitted) clockwise until the inner pad just touches the rotor, then back off half a click.",
     "Turn the barrel adjuster at the lever or caliper anticlockwise to take up cable slack until the lever bites at about a third of its travel.",
     "Spin the wheel. A light, occasional touch is fine; constant drag isn't.", "If pads are below 0.5 mm, replace them and bed them in.", NULL },
   "3 mm hex (pad bolts on some calipers), 5 mm hex for the cable clamp.", "the lever still reaches the bar after adjusting. This is a safety problem.",
   { P_CALIPERS, P_CABLES, P_LEVERS, P_ROTORS, END }, B_BRAKES },
 { "Spongy or soft lever (hydraulic)", "The lever squishes and the bite point wanders, often after the bike has been upside down.",
   SYS_BRAKE, 3, "30–60 min", "Medium",
   { "Air in the system: air compresses, oil doesn't.", "Fluid leak at a hose fitting or piston seal.", "Pads worn out, so the pistons are over-extended.", NULL },
   "Squeeze the lever hard. If it slowly creeps toward the bar, suspect a leak; if it feels soft but stops firmly, suspect air.",
   { "Try the quick fix: tilt the bike so the lever is the highest point, tap the hose, and pump the lever slowly 20 times. Air rises to the reservoir.",
     "If still soft, bleed with Shimano mineral oil (never DOT fluid) using a bleed funnel and syringe.", "Check pads and fittings for oil. Contaminated pads must be replaced.", NULL },
   "Shimano bleed kit and mineral oil, 7/8 mm spanner, rags.", "you see oil on the pads or rotor, or the lever goes all the way to the bar.",
   { P_CALIPERS, P_LEVERS, P_CABLES, END }, B_BRAKES },
 { "Brakes squeal, judder or feel weak", "The lever feels firm but the bike won't stop well, or the brakes howl.",
   SYS_BRAKE | SYS_NOISE, 2, "15–30 min", "Easy",
   { "Contaminated pads or rotor: oil, chain lube or tyre sealant.", "Pads not bedded in after replacement.", "Glazed pads from dragging on long descents.", NULL },
   "Smell the pads. Oily or shiny-black pads are contaminated.",
   { "Clean the rotors with isopropyl alcohol and a clean rag. Never touch the braking surface with bare fingers.", "If the pads are contaminated, replace them. Sanding rarely works.",
     "Bed in: ride to 20 km/h and brake firmly to walking pace, 10–20 times per brake, without locking up.", "Keep chain lube spray far away from the rotors.", NULL },
   "Isopropyl alcohol, clean rags, new pads.", "juddering persists after cleaning and bedding in. The rotor may be warped or the caliper loose.",
   { P_CALIPERS, P_ROTORS, END }, B_BRAKES },
 { "Brake rubs or ticks every wheel turn", "A shhh or tick-tick that matches wheel speed.",
   SYS_BRAKE | SYS_NOISE | SYS_WHEEL, 1, "10 min", "Easy",
   { "Wheel not seated: thru-axle not fully tightened.", "Caliper misaligned with the rotor.", "Bent rotor.", NULL },
   "Spin the wheel and look through the caliper toward a light. Watch the gaps either side of the rotor.",
   { "Open the thru-axle, push the wheel firmly into the dropouts, and retighten to the printed torque.",
     "Loosen both caliper mounting bolts slightly. Squeeze and hold the brake lever, then tighten the bolts alternately. Release and spin.",
     "If one spot ticks, find it and gently straighten the rotor with a rotor truing tool.", NULL },
   "5 mm hex (or Torx T25), rotor truing tool.", "the rotor is visibly dished or the mount is damaged.",
   { P_ROTORS, P_CALIPERS, P_THRUAXLE, END }, B_BRAKES },
 { "Flat tyre, or flat after flat", "Slow leaks, sudden flats, or two neat slits in the tube.",
   SYS_WHEEL, 2, "15 min", "Easy",
   { "Pinch flat (snakebite, two slits): pressure too low for a tube on rough ground.", "Puncture: something is still stuck in the tyre.",
     "Damaged rim tape: the hole is on the inside of the tube.", "Tubeless sealant dried out.", NULL },
   "Find the hole in the tube. Two parallel slits mean a pinch; one hole on the outside means a puncture; on the inside, the rim tape.",
   { "Open the thru-axle and remove the wheel.", "Unseat the tyre with levers, pull the tube, find the hole.",
     "Run your fingers carefully inside the tyre to find the culprit, matching the tube's hole to the tyre position.",
     "Fit a new tube with a little air in it, seat the tyre by hand, and check no tube is trapped under the bead.",
     "Inflate to the pressure from the Wheels bench. Tubeless: top up sealant every 2–4 months.", NULL },
   "Tyre levers, pump, spare tube or plug kit.", "the tyre has a cut big enough to see the tube through.",
   { P_TIRES, P_WHEELS, END }, B_WHEELS },
 { "Wheel wobbles or rubs the frame", "The rim wavers side to side as it spins.",
   SYS_WHEEL, 2, "10–40 min", "Medium",
   { "Thru-axle loose: the whole wheel shifts.", "Loose or broken spoke.", "Hub bearing play.", NULL },
   "Squeeze pairs of spokes all round the wheel. A slack one feels different immediately.",
   { "Tighten the thru-axle and re-check.", "Find the wobble with a zip tie on the frame as a pointer. Where the rim moves toward the tie, loosen the spoke on that side a quarter turn and tighten the opposite one a quarter turn.",
     "Replace any broken spoke before truing.", "Rock the rim sideways: play there is the hub, which needs a bearing service.", NULL },
   "Spoke key that fits your nipples, zip tie.", "more than one spoke is broken, or the wobble is over about 2 mm.",
   { P_WHEELS, P_HUBS, P_THRUAXLE, END }, B_WHEELS },
 { "Pedals spin without driving the wheel", "Pedals turn but the bike doesn't go, or the pedals keep turning while you coast.",
   SYS_DRIVE | SYS_WHEEL, 3, "30 min", "Medium",
   { "Freehub pawls stuck: old grease gone thick in the cold (won't engage), or seized (cranks turn when coasting).", NULL },
   "Lift the back wheel and pedal by hand. Listen for the click when you stop.",
   { "Remove the cassette and the axle end caps.", "Pull the freehub body; clean the pawls and the ratchet ring.",
     "Use a thin freehub grease or light oil on the pawls. Thick grease is the usual cause of failure to engage.", "Reassemble and test.", NULL },
   "Cassette lockring tool, chain whip, hub-specific tools.", "the pawls or ratchet teeth are chipped.",
   { P_HUBS, P_CASSETTE, END }, B_WHEELS },
 { "Clunk when braking hard, or steering knock", "A knock from the front over bumps or under front braking.",
   SYS_STEER | SYS_NOISE, 2, "10 min", "Easy",
   { "Headset preload too loose.", "Thru-axle loose (feels similar).", NULL },
   "Hold the front brake, put your fingers around the gap between the head tube and the spacer above it, and rock the bike. Movement there is headset play.",
   { "Loosen the two stem clamp bolts so the stem can slide.", "Tighten the top cap bolt in 1/8 turns until the play goes and the bar still swings freely.",
     "Line the stem up with the front wheel.", "Tighten the stem bolts alternately to the torque printed on the stem (usually about 5 Nm).", NULL },
   "4 or 5 mm hex, torque wrench.", "play remains with the top cap snug: the bearings or the compression ring are worn.",
   { P_HEADSET, P_COCKPIT, P_FORK, END }, B_STEER },
 { "Steering feels tight or notchy", "The bar doesn't fall to the side freely, or clicks into straight-ahead.",
   SYS_STEER, 2, "10–40 min", "Medium",
   { "Preload too tight.", "Worn or corroded bearings: notching in one spot.", NULL },
   "Lift the front wheel and swing the bar slowly. It should be smooth and fall to one side under its own weight.",
   { "Loosen the stem bolts, back off the top cap 1/8 turn, retighten the stem bolts.", "If notching remains in the straight-ahead position, the lower bearing is worn. Replace the cartridge bearings.", NULL },
   "4/5 mm hex, new cartridge bearings.", "the bearing seat in the frame looks damaged.",
   { P_HEADSET, END }, B_STEER },
 { "Creak or click while pedalling", "A rhythmic creak once per pedal stroke or per wheel turn.",
   SYS_NOISE | SYS_STEER | SYS_DRIVE, 1, "15–60 min", "Medium",
   { "Dry pedal threads (clicks once per stroke).", "Thru-axles not tight or not greased.", "Seatpost or saddle rails: pedal out of the saddle; if the noise stops, it's up there.",
     "Bottom bracket, only after the others are ruled out.", "Loose chainring bolts.", NULL },
   "Work by elimination. Pedal standing: silence points to the seat area. Pedal with one leg: noise on one side points to that pedal or crank.",
   { "Remove the pedals, grease the threads, refit (the left pedal is reverse-threaded).", "Remove both thru-axles, wipe, grease lightly, refit to torque.",
     "Remove the seatpost, clean, grease (carbon paste for carbon), refit; check the saddle rail bolts.", "Check chainring bolts and crank pinch bolts.",
     "Last: remove the threaded bottom bracket cups, clean, grease the threads, refit to torque.", NULL },
   "Pedal spanner or 8 mm hex, grease, bottom bracket tool for your cups.", "you hear grinding (not creaking) from the bottom bracket when spinning without the chain.",
   { P_BB, P_PEDALS, P_CRANKSET, P_SEATPOST, P_SADDLE, P_THRUAXLE, END }, B_STEER },
 { "Seatpost slips or saddle tilts", "The saddle slowly sinks or its nose drops during rides.",
   SYS_STEER, 1, "10 min", "Easy",
   { "Clamp under-torqued.", "Wrong compound: too much grease where friction paste is needed.", "Saddle rail clamp bolts loose.", NULL },
   "Mark the post at the clamp with tape and ride.",
   { "Clean the post and the inside of the seat tube.", "Apply a thin layer of friction (carbon assembly) paste.",
     "Set the height and tighten the seat clamp to its printed torque (often 5–6 Nm).", "Tighten the saddle rail bolts evenly to their printed torque.", NULL },
   "Torque wrench, 4/5 mm hex, friction paste.", "the post still slips at the maximum torque.",
   { P_SEATPOST, P_SADDLE, END }, -1 },
 { "Shift lever has no resistance", "The lever flops, or the derailleur sits stuck on the smallest cog.",
   SYS_SHIFT, 2, "20–40 min", "Medium",
   { "Snapped inner cable, usually frayed inside the lever head.", "Cable clamp bolt slipped at the derailleur.", NULL },
   "Look at the cable at the derailleur clamp. If it's slack and loose, check the lever end.",
   { "Shift the lever to the smallest-cog position.", "Peel back the hood rubber and pull the old cable head out of the lever.",
     "Feed a new inner cable through the lever and existing housing to the derailleur.", "Pull it taut, clamp it at the derailleur, cut and crimp the end, then index the gears.", NULL },
   "Cable cutters, 5 mm hex, end crimps.", "the lever itself is broken internally; levers aren't serviceable.",
   { P_LEVERS, P_CABLES, P_RD, END }, B_RD },
};
const int NPROBS = (int)(sizeof PROBS / sizeof PROBS[0]);

const Run RUNS[] = {
 { "Pedal power to the ground", "Follow your leg force from pedal to tyre.", {
   { P_PEDALS, "Your foot pushes the pedal down. Peak force arrives around the 3 o'clock position.", A_PEDAL_ON },
   { P_CRANKSET, "The crank arm is a lever: 170 mm of arm turns that force into torque on the axle.", A_NONE },
   { P_BB, "The bottom bracket bearings let the axle spin while holding it firmly in the frame.", A_NONE },
   { P_CHAIN, "The chainring pulls the top run of chain tight. Only the top run carries load.", A_NONE },
   { P_CASSETTE, "The chain pulls the selected cog. A smaller cog turns more times per pedal stroke: harder, faster.", A_NONE },
   { P_HUBS, "Pawls in the freehub catch the hub shell and pass the torque into the wheel.", A_NONE },
   { P_WHEELS, "The hub pulls on the spokes, and the spokes pull the rim around.", A_NONE },
   { P_TIRES, "The tyre pushes back against the ground at the contact patch, and the bike moves forward.", A_NONE },
   { P_FRAME, "Meanwhile the frame resists the chain's pull between the bottom bracket and rear axle. A stiff frame wastes less.", A_NONE } }, 9 },
 { "A rear shift", "From a click at the lever to the chain landing on a new cog.", {
   { P_LEVERS, "Swing the right lever inward. The shifter pulls a fixed length of cable per click.", A_PEDAL_ON },
   { P_CABLES, "The cable slides inside its housing, through the frame, to the rear derailleur.", A_NONE },
   { P_RD, "The extra pull moves the parallelogram inboard, swinging the jockey wheels under the next bigger cog.", A_SHIFT_EASIER },
   { P_CHAIN, "The chain is pushed sideways. Ramps on the bigger cog catch it, and it climbs over in less than one pedal stroke.", A_NONE },
   { P_CASSETTE, "Now it's on a bigger cog: an easier gear and a lower speed per pedal turn.", A_NONE },
   { P_RD, "The derailleur cage also swings forward to take up slack, keeping the bottom run of chain taut.", A_NONE },
   { P_HANGER, "All of this depends on the hanger holding the derailleur exactly parallel to the cogs.", A_NONE } }, 7 },
 { "Braking", "How a squeeze of the lever stops the bike.", {
   { P_LEVERS, "Pull the lever. Its leverage multiplies your finger force several times.", A_BRAKE_ON },
   { P_CABLES, "Mechanical: the cable pulls the caliper arm. Hydraulic: a piston pushes mineral oil down the hose.", A_NONE },
   { P_CALIPERS, "The caliper squeezes the pads onto both sides of the rotor.", A_NONE },
   { P_ROTORS, "Friction turns your speed into heat in the rotor and pads.", A_NONE },
   { P_HUBS, "The rotor is bolted to the hub, so the hub slows.", A_NONE },
   { P_WHEELS, "The hub drags on the spokes, which slow the rim.", A_NONE },
   { P_TIRES, "The tyre's grip on the ground is the final limit. Brake harder than that and it skids.", A_NONE },
   { P_FORK, "At the front, braking force tries to bend the fork backwards and loads the headset. That's why headset play shows up as a clunk when you brake.", A_BRAKE_OFF } }, 8 },
 { "Steering", "From your hands to the front tyre.", {
   { P_COCKPIT, "Your hands turn the bar; the stem clamps it to the fork's steerer tube.", A_NONE },
   { P_HEADSET, "The steerer turns inside two headset bearings. Preload removes rattle without binding.", A_NONE },
   { P_FORK, "The fork turns about the steering axis. The tyre touches the ground behind where that axis meets it (trail), so the wheel self-centres.", A_NONE },
   { P_THRUAXLE, "The thru-axle holds the front wheel rigidly in the fork, so it goes exactly where the bar points.", A_NONE },
   { P_TIRES, "The tyre deforms slightly to generate cornering grip.", A_NONE } }, 5 },
 { "Your weight and comfort", "Where your weight goes, and what absorbs the bumps.", {
   { P_SADDLE, "Most of your weight sits on the saddle.", A_NONE },
   { P_SEATPOST, "The seatpost flexes slightly. A longer exposed post flexes more.", A_NONE },
   { P_FRAME, "The frame carries the load to both axles through its two triangles.", A_NONE },
   { P_COCKPIT, "Some weight is on your hands, through the bar, stem and fork.", A_NONE },
   { P_TIRES, "The tyres are the real suspension: at gravel pressures they deflect a few millimetres over every bump.", A_NONE } }, 5 },
};
const int NRUNS = (int)(sizeof RUNS / sizeof RUNS[0]);

const BenchInfo BENCHES[B_COUNT] = {
 { "Gearing", "Ratios, chainline, cross-chaining",
   "A gear is a ratio: chainring teeth ÷ cog teeth. One crank turn rotates the rear wheel that many times. Multiply by the wheel's 2.19 m circumference and you get the distance per pedal stroke. The view looks along the drivetrain from behind, so you can see the chain angle change as you shift.",
   "Using two rings", { "Stay in the big ring on flats and descents, the small ring for climbs.", "Use the cassette for small steps between gears.",
     "Avoid big ring with the biggest cogs, and small ring with the smallest cogs.", "Shift the front before you need it: front shifts under heavy load drop chains.", NULL },
   {230, 330, 40}, 1800, -72, 55 },
 { "Rear derailleur", "Cable tension, limit screws, hanger",
   "Seen from behind. The cable pulls the parallelogram inward toward bigger cogs; the spring pulls it back out. The limit screws are hard stops at each end. Each click of the lever should move the guide pulley exactly one cog spacing.",
   "Indexing in four steps", { "Smallest cog: set H so the guide pulley sits right under the cog.", "Largest cog: set L the same way, pushing the derailleur inward to test.",
     "Second cog: tune the barrel adjuster until it runs silently and shifts crisply both ways.", "Check every cog. Errors that grow toward the big cogs point to the hanger.", NULL },
   {20, 330, 40}, 1050, -62, 14 },
 { "Front derailleur", "Cage position, trim, limits",
   "The cage is two plates either side of the chain. The outer plate pushes the chain up onto the big ring; the inner plate pushes it down to the small ring. Which rear cog you're in changes the chain's angle through the cage.",
   "Good to know", { "On the small ring the cable is slack, and the spring holds the cage against the L screw.", "On the big ring, cable tension sets the position and the H screw stops overshoot.",
     "Cage height: outer plate 1–3 mm above the big ring's teeth, parallel to it.", NULL },
   {360, 370, 40}, 1000, -50, 30 },
 { "Brakes", "Lever, cable or oil, pads, rotor",
   "Looking down on the caliper. A mechanical caliper pushes only the outer pad, with a cam, and the rotor flexes onto the fixed inner pad. A hydraulic caliper pushes both pads with oil, and its pistons self-adjust as pads wear.",
   "Pad replacement", { "Remove the wheel.", "Remove the pad retaining pin or bolt and pull the pads out.",
     "Mechanical: back the inner pad dial fully out. Hydraulic: push the pistons back with a plastic tyre lever.", "Fit new pads and spring; refit the pin.",
     "Adjust as on this bench, or pump the lever until it firms up.", "Bed in: 10–20 firm stops from 20 km/h.", NULL },
   {60, 380, -58}, 1050, 205, 30 },
 { "Wheels & tyres", "Pressure, contact patch, freehub",
   "Tyre pressure decides the size of the contact patch and how far the tyre can deflect before the rim hits. Inside the rear hub, the freehub's pawls catch a toothed ring when you pedal and click over it when you coast.",
   "Thru-axles", { "To remove a wheel: open the lever (or use a 6 mm hex), unscrew fully, pull the axle out.",
     "On refit, push the wheel fully into the dropouts first so the rotor drops into the caliper slot.", "Tighten by hand to the torque printed on the axle.", NULL },
   {60, 330, 0}, 2300, 28, 8 },
 { "Headset & bottom bracket", "Preload, bearing order, BB threads",
   "The top cap bolt pulls the stem down, which presses the headset bearings together (preload). The stem bolts then lock it. The threaded bottom bracket is two cups screwed into the frame with the crank axle running through them.",
   "Adjustment order", { "Loosen both stem clamp bolts.", "Tighten the top cap until play disappears, 1/8 turn at a time.", "Align the stem with the front wheel.",
     "Tighten the stem bolts alternately to the printed torque.", "Recheck: brake on, rock the bike. Then lift the front: the bar should fall freely.", NULL },
   {780, 700, 0}, 1700, 35, 12 },
};
